schema_version: 1

context:
  name: django-nyt
  version: 1.4.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_nyt-${{ version }}.tar.gz
  sha256: 1917cab2fc1d75bd99612b672c1555311515f55ee4ad51cb910f3ecc5516e666

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - django >=2.2,<5.3

tests:
  - python:
      imports:
        - django_nyt
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: A pluggable notification system written for the Django framework.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/django-wiki/django-nyt
  repository: https://github.com/django-wiki/django-nyt

extra:
  recipe-maintainers:
    - rxm7706
